# Generated by Django 3.1.3 on 2020-12-07 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.IntegerField(max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('contact_num', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_code', models.IntegerField(max_length=8)),
                ('discount_type', models.CharField(choices=[('F', 'Flat'), ('P', 'Percent')], default='F', max_length=1)),
                ('valid_before', models.DateField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_id', models.IntegerField(max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('contact_num', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(max_length=8)),
                ('wage', models.FloatField()),
                ('join_date', models.DateField(auto_now_add=True)),
                ('employed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_id', models.IntegerField()),
                ('model', models.CharField(max_length=50)),
                ('date_aquired', models.DateField()),
                ('eq_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.IntegerField(max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('stock_quantity', models.IntegerField()),
                ('sales_price', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(max_length=8)),
                ('payment_method', models.CharField(max_length=50)),
                ('customer_email', models.CharField(max_length=50)),
                ('subtotal', models.FloatField()),
                ('sales_tax', models.FloatField()),
                ('total', models.FloatField()),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.item')),
                ('ac_type', models.CharField(max_length=50)),
            ],
            bases=('api.item',),
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.item')),
                ('material', models.CharField(max_length=50)),
                ('cl_type', models.CharField(max_length=50)),
            ],
            bases=('api.item',),
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.equipment')),
                ('description', models.CharField(max_length=50)),
            ],
            bases=('api.equipment',),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.employee')),
                ('man_id', models.IntegerField(max_length=8)),
                ('man_type', models.CharField(max_length=5)),
            ],
            bases=('api.employee',),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.transaction')),
                ('profit', models.FloatField()),
            ],
            bases=('api.transaction',),
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.transaction')),
            ],
            bases=('api.transaction',),
        ),
        migrations.CreateModel(
            name='Till',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.equipment')),
                ('serial_no', models.IntegerField(max_length=8)),
                ('operating_system', models.CharField(max_length=50)),
            ],
            bases=('api.equipment',),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('manager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.manager')),
                ('admin_id', models.IntegerField(max_length=8)),
            ],
            bases=('api.manager',),
        ),
        migrations.CreateModel(
            name='Bottom',
            fields=[
                ('clothing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.clothing')),
                ('waist', models.IntegerField(max_length=2)),
                ('length', models.IntegerField(max_length=2)),
            ],
            bases=('api.clothing',),
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('clothing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.clothing')),
                ('size', models.CharField(choices=[('XS', 'Extra-Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large')], default='M', max_length=2)),
            ],
            bases=('api.clothing',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='serial_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.till'),
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.transaction')),
                ('reason', models.CharField(max_length=50)),
                ('original_tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_tid', to='api.transaction')),
            ],
            bases=('api.transaction',),
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(max_length=50)),
                ('incident_date', models.DateField()),
                ('filing_date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=50)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_id', to='api.employee')),
                ('man_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_id', to='api.manager')),
            ],
        ),
    ]
