# Generated by Django 3.1.3 on 2020-12-07 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='eid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_id', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='man_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_id', to='api.manager'),
        ),
        migrations.AlterField(
            model_name='return',
            name='original_tid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_tid', to='api.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='eid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee'),
        ),
    ]
