# Generated by Django 3.1.4 on 2020-12-07 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201207_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='b_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.brand'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='serial_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.till'),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transaction')),
            ],
        ),
    ]
