# Generated by Django 3.1.4 on 2020-12-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201206_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='admin_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='bottom',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bottom',
            name='waist',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='brand',
            name='b_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='contact_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='c_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='contact_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='dist_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eq_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='upc',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='man_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='till',
            name='serial_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
