# Generated by Django 3.1.4 on 2020-12-08 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201208_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.distributor')),
                ('item_upd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.item')),
            ],
        ),
    ]
