# Generated by Django 3.1.4 on 2020-12-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_coupon_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('F', 'Flat'), ('P', 'Percent')], default='F', max_length=1),
        ),
    ]
