# Generated by Django 3.1.4 on 2020-12-09 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_coupon_discount_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('revenue', models.FloatField()),
                ('sales_tax', models.FloatField()),
                ('profit', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='distributes',
            name='dist_id',
        ),
        migrations.AddField(
            model_name='distributes',
            name='dist_id',
            field=models.ManyToManyField(to='api.Distributor'),
        ),
        migrations.AlterField(
            model_name='distributes',
            name='item_upc',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api.item'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_code', models.ManyToManyField(to='api.Coupon')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transaction')),
            ],
        ),
    ]
